# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [7]:
#1.1

# np.arange(1, 26).reshape(5,5)

array = np.random.randint(1, 20, (5, 5))
print(array)

[[ 9 11  8 15  7]
 [ 3  8 14 10  7]
 [13  7  4  7 10]
 [15 11 15  5  5]
 [16  8  9  3  2]]


In [19]:
array[:, 2] = 1

print(array)

[[ 9 11  1 15  7]
 [ 3  8  1 10  7]
 [13  7  1  7 10]
 [15 11  1  5  5]
 [16  8  1  3  2]]


In [21]:
#1.2

arrary = np.arange(1, 17).reshape(4, 4)
print(arrary)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
np.fill_diagonal(arrary, 0)
print(arrary)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [24]:
# 2.1

array = np.arange(1, 37).reshape(6,6)
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [30]:
sub_arrary = array[2:5, 1:4]
print(sub_arrary)

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [33]:
# 2.2

array = np.random.randint(1, 20, (5, 5))
print(array)


[[ 6 14  2 15 19]
 [17 19  9  2  7]
 [16  5 19 15  8]
 [ 4 19  4  6 19]
 [13 17 11  9 12]]


In [41]:
border_element = np.concatenate((array[0], array[-1], array[1:-1, 0], array[1:-1, -1]))

print(border_element)

[ 6 14  2 15 19 13 17 11  9 12 17 16  4  7  8 19]


In [43]:
# 3.1

arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3,4))

print(arr1)
print(arr2)

add_arr = arr1 + arr2
sub_arr = arr1 - arr2
mul_arr = arr1 * arr2
div_arr = arr1 / arr2

print('Addition\n',add_arr)
print('Subtraction\n',sub_arr)
print('Multiplication\n',mul_arr)
print('Division\n',div_arr)

[[6 4 7 4]
 [9 1 1 7]
 [8 8 9 5]]
[[6 8 7 7]
 [7 2 4 1]
 [2 3 1 9]]
Addition
 [[12 12 14 11]
 [16  3  5  8]
 [10 11 10 14]]
Subtraction
 [[ 0 -4  0 -3]
 [ 2 -1 -3  6]
 [ 6  5  8 -4]]
Multiplication
 [[36 32 49 28]
 [63  2  4  7]
 [16 24  9 45]]
Division
 [[1.         0.5        1.         0.57142857]
 [1.28571429 0.5        0.25       7.        ]
 [4.         2.66666667 9.         0.55555556]]


In [48]:
# 3.2

arr = np.arange(1, 17).reshape(4, 4)

print(arr)

row_add_arr = np.sum(arr, axis=1)
column_add_arr = np.sum(arr, axis=0)

print('Row Addition\n',row_add_arr)
print('Column Addition\n',column_add_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row Addition
 [10 26 42 58]
Column Addition
 [28 32 36 40]


In [49]:
# 4.1

array = np.random.randint(1, 21, (5, 5))
print(array)

print("Mean\n", np.mean(array))
print("Median\n", np.median(array))
print("Standard Deviation\n", np.std(array))
print("Variance\n", np.var(array))

[[ 9 20 13 16 18]
 [ 8 15  9 11 12]
 [20  8 10 18  1]
 [ 6 14 10  3 20]
 [ 8  5  8 10 12]]
Mean
 11.36
Median
 10.0
Standard Deviation
 5.160465095318444
Variance
 26.630399999999998


In [50]:
# 4.2

arr = np.arange(1, 10).reshape(3, 3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_data = (arr - mean) / std_dev

print(normalized_data)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [54]:
# 5.1

arr = np.random.randint(1, 10, (3, 3))
arr_1d = np.random.randint(1, 10, (3))

print("3D Array\n",arr)
print("1D Array\n", arr_1d)

array = arr + arr_1d
print(array)

3D Array
 [[4 8 8]
 [7 6 1]
 [7 7 1]]
1D Array
 [6 1 6]
[[10  9 14]
 [13  7  7]
 [13  8  7]]


In [58]:
# 5.2

arr = np.random.randint(1, 17, (4, 4))
arr_1d = np.random.randint(1, 10, (4))

print("3D Array\n",arr)
print("1D Array\n", arr_1d)

arr_1dd = arr_1d[:, np.newaxis]
print(arr_1dd)

result = arr - arr_1dd

print(result)

3D Array
 [[11  3  1  5]
 [15  7  2  3]
 [12 15 15 11]
 [ 1  9  4  6]]
1D Array
 [1 1 6 7]
[[1]
 [1]
 [6]
 [7]]
[[10  2  0  4]
 [14  6  1  2]
 [ 6  9  9  5]
 [-6  2 -3 -1]]


In [ ]:
# 6.1

