# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.


In [1]:
!pip install pandas
!pip install numpy

In [7]:
# 1.1

import pandas as pd
import numpy as np

array = np.random.randint(1, 10, size=(6, 4))
print(array, "\n")

df = pd.DataFrame(array, columns=['A', 'B', 'C', 'D'])
print(df, "\n")

df.set_index('A', inplace=True)
print(df, "\n")

[[2 5 3 1]
 [4 6 6 3]
 [1 5 8 8]
 [9 8 6 6]
 [8 1 5 2]
 [9 2 4 8]] 

   A  B  C  D
0  2  5  3  1
1  4  6  6  3
2  1  5  8  8
3  9  8  6  6
4  8  1  5  2
5  9  2  4  8 

   B  C  D
A         
2  5  3  1
4  6  6  3
1  5  8  8
9  8  6  6
8  1  5  2
9  2  4  8 



In [11]:
# 1.2

arr = np.random.randint(1, 10, size=(3, 3))
print(arr, "\n")

df = pd.DataFrame(arr, columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print(df, "\n")

element = df.at['Y', 'B']
print(element)

[[2 4 3]
 [4 8 7]
 [8 3 8]] 

   A  B  C
X  2  4  3
Y  4  8  7
Z  8  3  8 

8


In [13]:
# 2.1

arr = np.random.randint(1, 10, (5, 3))
print(arr, "\n")

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df, "\n")

df['D'] = df['A'] * df['B']
print(df, "\n")



[[9 8 5]
 [4 3 8]
 [2 3 1]
 [4 9 4]
 [8 8 4]] 

   A  B  C
0  9  8  5
1  4  3  8
2  2  3  1
3  4  9  4
4  8  8  4 

   A  B  C   D
0  9  8  5  72
1  4  3  8  12
2  2  3  1   6
3  4  9  4  36
4  8  8  4  64 



In [14]:
# 2.2

arr = np.random.randint(1, 10, (4, 3))
print(arr, "\n")

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df, "\n")

row_sum = df.sum(axis=1)
column_sum = df.sum(axis=0)

print(row_sum, "\n")
print(column_sum, "\n")

[[7 8 4]
 [9 7 8]
 [8 4 3]
 [5 4 4]] 

   A  B  C
0  7  8  4
1  9  7  8
2  8  4  3
3  5  4  4 

0    19
1    24
2    15
3    13
dtype: int64 

A    29
B    23
C    19
dtype: int64 



In [17]:
# 3.1

df = pd.DataFrame(np.random.randint(1, 10, (5, 3)), columns=['A', 'B', 'C'])
print(df, "\n")

df.iloc[2, 1] = np.nan
df.iloc[3, 2] = np.nan
df.iloc[4, 0] = np.nan
print(df, "\n")

df.fillna(df.mean(), inplace=True)
print(df, "\n")

   A  B  C
0  7  1  4
1  3  1  5
2  4  3  5
3  5  3  6
4  1  6  3 

     A    B    C
0  7.0  1.0  4.0
1  3.0  1.0  5.0
2  4.0  NaN  5.0
3  5.0  3.0  NaN
4  NaN  6.0  3.0 

      A     B     C
0  7.00  1.00  4.00
1  3.00  1.00  5.00
2  4.00  2.75  5.00
3  5.00  3.00  4.25
4  4.75  6.00  3.00 



In [21]:
# 3.2

df = pd.DataFrame(np.random.randint(1, 10, (6, 4)), columns=['A', 'B', 'C', 'D'])
print(df, "\n")

df.iloc[2, 1] = np.nan
df.iloc[3, 2] = np.nan
df.iloc[4, 0] = np.nan
print(df, "\n")

df.dropna(inplace=True)
print(df, "\n")

   A  B  C  D
0  9  1  1  7
1  2  2  5  9
2  9  5  2  6
3  4  6  5  4
4  8  3  9  7
5  2  4  3  4 

     A    B    C  D
0  9.0  1.0  1.0  7
1  2.0  2.0  5.0  9
2  9.0  NaN  2.0  6
3  4.0  6.0  NaN  4
4  NaN  3.0  9.0  7
5  2.0  4.0  3.0  4 

     A    B    C  D
0  9.0  1.0  1.0  7
1  2.0  2.0  5.0  9
5  2.0  4.0  3.0  4 



In [25]:
# 4.1

df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], 10),
    'Value': np.random.randint(1, 10, 10)})
print(df, "\n")

x = df.groupby('Category')['Value'].agg(['sum', 'mean', 'median'])
print(x, "\n")


  Category  Value
0        C      3
1        B      9
2        C      9
3        B      1
4        B      6
5        A      6
6        A      1
7        A      7
8        B      2
9        C      8 

          sum      mean  median
Category                       
A          14  4.666667     6.0
B          18  4.500000     4.0
C          20  6.666667     8.0 



In [28]:
# 4.2

df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], 10),
    'Category': np.random.choice(['A', 'B', 'C'], 10),
    'Sales': np.random.randint(1, 10, 10)})

print(df, "\n")

x = df.groupby('Category')['Sales'].sum()
print(x, "\n")


  Product Category  Sales
0   Prod1        B      9
1   Prod2        C      3
2   Prod2        A      6
3   Prod2        C      3
4   Prod1        A      4
5   Prod1        C      7
6   Prod3        C      2
7   Prod1        C      6
8   Prod3        A      3
9   Prod2        C      6 

Category
A    13
B     9
C    27
Name: Sales, dtype: int32 



In [33]:
# 5.1

df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'], 'Value1': np.random.randint(1, 10, size=4)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E'], 'Value2': np.random.randint(1, 10, size=4)})
print(df1, "\n")
print(df2, "\n")

df3 = pd.merge(df1, df2, on='Key')
print(df3, "\n")

  Key  Value1
0   A       5
1   B       4
2   C       8
3   D       1 

  Key  Value2
0   A       2
1   B       5
2   C       8
3   E       2 

  Key  Value1  Value2
0   A       5       2
1   B       4       5
2   C       8       8 



In [38]:
# 5.2

df1 = pd.DataFrame({'A': np.random.randint(1, 10, 3), 'B': np.random.randint(1, 10, 3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 10, 3), 'D': np.random.randint(1, 10, 3)})

print(df1, "\n")
print(df2, "\n")

# axis=0 for row and axis=1 for column
df3 = pd.concat([df1, df2], axis=1)
df4 = pd.concat([df1, df2], axis=0) 

print(df3, "\n")
print(df4, "\n")


   A  B
0  9  3
1  3  8
2  1  5 

   C  D
0  5  6
1  2  3
2  3  2 

   A  B  C  D
0  9  3  5  6
1  3  8  2  3
2  1  5  3  2 

     A    B    C    D
0  9.0  3.0  NaN  NaN
1  3.0  8.0  NaN  NaN
2  1.0  5.0  NaN  NaN
0  NaN  NaN  5.0  6.0
1  NaN  NaN  2.0  3.0
2  NaN  NaN  3.0  2.0 



In [51]:
# 6.1

date_rng = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df.set_index('date', inplace=True)
print(df)


monthly_mean = df.resample('M').mean()
print(monthly_mean, "\n")

            data
date            
2022-01-01    72
2022-01-02    97
2022-01-03     3
2022-01-04    24
2022-01-05     9
...          ...
2022-12-27    82
2022-12-28    20
2022-12-29    76
2022-12-30    78
2022-12-31    52

[365 rows x 1 columns]
                 data
date                 
2022-01-31  47.709677
2022-02-28  43.142857
2022-03-31  48.709677
2022-04-30  53.000000
2022-05-31  45.774194
2022-06-30  52.966667
2022-07-31  43.548387
2022-08-31  48.709677
2022-09-30  52.033333
2022-10-31  54.483871
2022-11-30  52.233333
2022-12-31  48.096774 



C:\Users\AbhayKumarVishwakarm\AppData\Local\Temp\ipykernel_30420\153944728.py:10: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_mean = df.resample('M').mean()


In [54]:
# 6.2

date_range = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df = pd.DataFrame(date_range, columns=['date'])
df['data'] = np.random.randint(1, 100, size=(len(date_range)))
df.set_index('date', inplace=True)
print(df, "\n")

rolling_mean = df.rolling(window=7).mean()
print(rolling_mean, "\n")

            data
date            
2022-01-01    12
2022-01-02     4
2022-01-03    56
2022-01-04    58
2022-01-05    94
...          ...
2022-12-27    22
2022-12-28    83
2022-12-29    48
2022-12-30     5
2022-12-31    84

[365 rows x 1 columns] 

                 data
date                 
2022-01-01        NaN
2022-01-02        NaN
2022-01-03        NaN
2022-01-04        NaN
2022-01-05        NaN
...               ...
2022-12-27  59.571429
2022-12-28  62.428571
2022-12-29  63.571429
2022-12-30  52.142857
2022-12-31  52.857143

[365 rows x 1 columns] 



In [ ]:
arrays = [['A', 'A', 'A', 'B', 'B', 'B'], ['one', 'two', 'three', 'one', 'two', 'three']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))

df = pd.DataFrame(np.random.randint(1, 10, (6, 4)), index=index, columns=['Value1', 'Value2', 'Value3', 'Value4'])
print(df, "\n")

print(df.loc['A', 'one'])




                      Value1  Value2  Value3  Value4
Category SubCategory                                
A        one               9       7       4       2
         two               1       1       7       8
         three             8       2       7       1
B        one               3       3       7       2
         two               5       6       4       9
         three             9       5       4       1 

Value1    9
Value2    7
Value3    4
Value4    2
Name: (A, one), dtype: int32


In [64]:
arrays = [['A', 'A', 'A', 'B'], ['one', 'two', 'one', 'two', ]]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 10, (4, 3)), index = index, columns=['Value1', 'Value2', 'Value3'])
print(df, "\n")        


sum_values = df.groupby(['Category', 'SubCategory']).sum()
print(sum_values, "\n")

                      Value1  Value2  Value3
Category SubCategory                        
A        one               7       9       4
         two               2       2       8
         one               3       8       5
B        two               3       2       3 

                      Value1  Value2  Value3
Category SubCategory                        
A        one              10      17       9
         two               2       2       8
B        two               3       2       3 



In [67]:
# 8.1

date_rang = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df = pd.DataFrame({'Date': np.random.choice(date_range, 20), 'Category': np.random.choice(['A', 'B', 'C'], 20), 'Value': np.random.randint(1, 10, 20)})
print(df, "\n")

pivot_table = df.pivot_table(values='Value', index='Date', columns='Category')
print(pivot_table, "\n")

         Date Category  Value
0  2022-02-18        A      3
1  2022-07-24        A      5
2  2022-09-24        C      5
3  2022-01-15        B      5
4  2022-01-26        B      2
5  2022-11-07        A      2
6  2022-05-23        B      3
7  2022-08-18        B      6
8  2022-11-02        B      8
9  2022-07-06        C      8
10 2022-09-13        C      5
11 2022-08-13        B      3
12 2022-02-19        A      2
13 2022-03-22        C      7
14 2022-01-06        A      8
15 2022-09-11        B      5
16 2022-03-01        B      5
17 2022-03-10        B      8
18 2022-11-13        B      9
19 2022-04-03        B      8 

Category      A    B    C
Date                     
2022-01-06  8.0  NaN  NaN
2022-01-15  NaN  5.0  NaN
2022-01-26  NaN  2.0  NaN
2022-02-18  3.0  NaN  NaN
2022-02-19  2.0  NaN  NaN
2022-03-01  NaN  5.0  NaN
2022-03-10  NaN  8.0  NaN
2022-03-22  NaN  NaN  7.0
2022-04-03  NaN  8.0  NaN
2022-05-23  NaN  3.0  NaN
2022-07-06  NaN  NaN  8.0
2022-07-24  5.0  NaN  NaN
2022

In [68]:
# 8.2

In [70]:
# 9.1

df = pd.DataFrame(np.random.randint(1, 10, (5, 3)), columns=['A', 'B', 'C'])
print(df, "\n")

df_d = df.applymap(lambda x: x * 2)
print(df_d, "\n")

   A  B  C
0  1  1  9
1  1  8  8
2  5  4  9
3  8  5  4
4  3  7  5 

    A   B   C
0   2   2  18
1   2  16  16
2  10   8  18
3  16  10   8
4   6  14  10 



C:\Users\AbhayKumarVishwakarm\AppData\Local\Temp\ipykernel_30420\1811114181.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_d = df.applymap(lambda x: x * 2)


In [71]:
# 9.2

In [74]:
# 10.1

text_data = pd.Series(['apple', 'banana', 'cherry', 'apple', 'banana', 'cherry'])
print(text_data, "\n")

word_count = text_data.value_counts()
print(word_count, "\n")

up_data = text_data.str.upper()
print(up_data, "\n")

0     apple
1    banana
2    cherry
3     apple
4    banana
5    cherry
dtype: object 

apple     2
banana    2
cherry    2
Name: count, dtype: int64 

0     APPLE
1    BANANA
2    CHERRY
3     APPLE
4    BANANA
5    CHERRY
dtype: object 

